/**
 * Reports Routes — Daily/weekly reports generated by Fisher2050
 */

import { Router, Request, Response } from 'express';
import { getDb } from '../../db.js';
import { nanoid } from 'nanoid';
import { getPiaClient } from '../../integrations/pia.js';

const router = Router();

/** GET /api/reports — List reports */
router.get('/', (req: Request, res: Response) => {
  try {
    const db = getDb();
    const type = req.query.type as string;
    const limit = parseInt(req.query.limit as string) || 20;

    let query = 'SELECT * FROM reports';
    const params: unknown[] = [];

    if (type) { query += ' WHERE type = ?'; params.push(type); }
    query += ' ORDER BY created_at DESC LIMIT ?';
    params.push(limit);

    const reports = db.prepare(query).all(...params);
    res.json(reports);
  } catch (error) {
    res.status(500).json({ error: 'Failed to list reports' });
  }
});

/** GET /api/reports/:id — Get a report */
router.get('/:id', (req: Request, res: Response): void => {
  try {
    const db = getDb();
    const report = db.prepare('SELECT * FROM reports WHERE id = ?').get(req.params.id);
    if (!report) { res.status(404).json({ error: 'Report not found' }); return; }
    res.json(report);
  } catch (error) {
    res.status(500).json({ error: 'Failed to get report' });
  }
});

/** POST /api/reports/generate — Generate a daily report */
router.post('/generate', async (req: Request, res: Response): Promise<void> => {
  try {
    const db = getDb();
    const type = (req.body.type || 'daily') as string;

    // Gather data for report
    const activeProjects = db.prepare("SELECT * FROM projects WHERE status = 'active'").all() as any[];
    const overdueTasks = db.prepare("SELECT t.*, p.name as project_name FROM tasks t LEFT JOIN projects p ON t.project_id = p.id WHERE t.status IN ('pending','in_progress') AND t.due_date < unixepoch()").all();
    const recentTasks = db.prepare("SELECT t.*, p.name as project_name FROM tasks t LEFT JOIN projects p ON t.project_id = p.id WHERE t.updated_at > unixepoch() - 86400 ORDER BY t.updated_at DESC").all();
    const upcomingMeetings = db.prepare("SELECT * FROM meetings WHERE status = 'scheduled' AND scheduled_at > unixepoch() AND scheduled_at < unixepoch() + 172800 ORDER BY scheduled_at").all();
    const recentActivity = db.prepare("SELECT * FROM activity_log ORDER BY created_at DESC LIMIT 20").all();

    // Build report content
    const now = new Date();
    const lines: string[] = [];

    lines.push(`# Fisher2050 ${type === 'daily' ? 'Daily' : 'Weekly'} Report`);
    lines.push(`**Date:** ${now.toISOString().split('T')[0]}`);
    lines.push('');

    lines.push('## Active Projects');
    if (activeProjects.length === 0) {
      lines.push('No active projects.');
    } else {
      activeProjects.forEach(p => {
        const taskCount = (db.prepare("SELECT COUNT(*) as c FROM tasks WHERE project_id = ? AND status != 'completed'").get(p.id) as any).c;
        lines.push(`- **${p.name}** — ${taskCount} open tasks`);
      });
    }
    lines.push('');

    lines.push('## Overdue Tasks');
    if ((overdueTasks as any[]).length === 0) {
      lines.push('No overdue tasks. Nice!');
    } else {
      (overdueTasks as any[]).forEach(t => {
        const dueDate = new Date(t.due_date * 1000).toISOString().split('T')[0];
        lines.push(`- **${t.title}** (${t.project_name || 'No project'}) — due ${dueDate}, assigned to ${t.assigned_to || 'unassigned'}`);
      });
    }
    lines.push('');

    lines.push('## Recent Activity (24h)');
    if ((recentTasks as any[]).length === 0) {
      lines.push('No task activity in the last 24 hours.');
    } else {
      (recentTasks as any[]).forEach(t => {
        lines.push(`- [${t.status}] **${t.title}** (${t.project_name || ''})`);
      });
    }
    lines.push('');

    lines.push('## Upcoming Meetings (48h)');
    if ((upcomingMeetings as any[]).length === 0) {
      lines.push('No upcoming meetings.');
    } else {
      (upcomingMeetings as any[]).forEach((m: any) => {
        const meetTime = new Date(m.scheduled_at * 1000).toLocaleString();
        lines.push(`- **${m.title}** — ${meetTime} (${m.duration_minutes}min)`);
      });
    }
    lines.push('');

    // Calculate project health
    const totalTasks = (db.prepare("SELECT COUNT(*) as c FROM tasks WHERE status != 'cancelled'").get() as any).c;
    const completedTasks = (db.prepare("SELECT COUNT(*) as c FROM tasks WHERE status = 'completed'").get() as any).c;
    const overdueCount = (overdueTasks as any[]).length;
    const health = totalTasks > 0 ? Math.round(((completedTasks / Math.max(totalTasks, 1)) * 70 + (1 - overdueCount / Math.max(totalTasks, 1)) * 30)) : 100;

    lines.push(`---`);
    lines.push(`**Project Health: ${Math.min(health, 100)}%**`);
    lines.push(`*— Fisher2050, Project Manager*`);

    const content = lines.join('\n');
    const id = nanoid();

    db.prepare(`
      INSERT INTO reports (id, type, title, content, created_at)
      VALUES (?, ?, ?, ?, ?)
    `).run(id, type, `${type === 'daily' ? 'Daily' : 'Weekly'} Report — ${now.toISOString().split('T')[0]}`, content, Math.floor(Date.now() / 1000));

    db.prepare('INSERT INTO activity_log (action, entity_type, entity_id, details) VALUES (?, ?, ?, ?)')
      .run('generate_report', 'report', id, `Generated ${type} report`);

    res.status(201).json({ id, type, content });
  } catch (error) {
    console.error('[Fisher2050] Report generation error:', error);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

/** POST /api/reports/trigger-review — Trigger Ziggi post-session review */
router.post('/trigger-review', async (req: Request, res: Response): Promise<void> => {
  try {
    const { projectDir, description } = req.body;
    if (!projectDir) { res.status(400).json({ error: 'projectDir is required' }); return; }

    const pia = getPiaClient();
    const result = await pia.triggerZiggiReview(projectDir, description);

    const db = getDb();
    db.prepare('INSERT INTO activity_log (action, entity_type, entity_id, details) VALUES (?, ?, ?, ?)')
      .run('trigger_review', 'task', result.taskId, `Triggered Ziggi review for ${projectDir}`);

    res.json(result);
  } catch (error) {
    console.error('[Fisher2050] Trigger review error:', error);
    res.status(500).json({ error: 'Failed to trigger review' });
  }
});

/** GET /api/reports/activity — Get activity log */
router.get('/activity/log', (req: Request, res: Response) => {
  try {
    const db = getDb();
    const limit = parseInt(req.query.limit as string) || 50;
    const activities = db.prepare('SELECT * FROM activity_log ORDER BY created_at DESC LIMIT ?').all(limit);
    res.json(activities);
  } catch (error) {
    res.status(500).json({ error: 'Failed to get activity log' });
  }
});

export default router;
